### ISSUE TITLE
Having a min and max range inside the month makes the whole month seem disabled.

### ISSUE THREAD

**Issue by caalador** [vaadin/vaadin-date-picker#573] opened 2018-06-11 10:26 UTC
### Description
Having a min and max range inside the month makes the whole month seem disabled even though the range is selectable.

Also if either start date is the first or end date is the last the whole month seems selectable.

### Expected outcome
Before min and after max are grayed out and the in-between is black.

### Actual outcome
Everything is grayed out.

### Live Demo
`<vaadin-date-picker label="June 2017" min="2017-06-05" max="2017-06-16" initial-position="2017-06-15" tabindex="0"></vaadin-date-picker>`

### Steps to reproduce
In the `Min and max dates` demo on vaadin.com set the min and max date to be inside the same mont.

Also see: https://github.com/vaadin/vaadin-date-picker-flow/issues/93

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by tomivirkki** [comment] 2018-06-11 10:56
Duplicate of https://github.com/vaadin/vaadin-date-picker/issues/560

Fixed in https://github.com/vaadin/vaadin-date-picker/pull/562

**Comment by limonte** [comment] 2018-06-11 11:00
And released in [v3.1.0](https://github.com/vaadin/vaadin-date-picker/releases/tag/v3.1.0)

**Closed by limonte** 2018-06-11 11:00 UTC

**Comment by tomivirkki** [comment] 2018-06-11 11:09
@limonte I think the problem is that the release was a minor version. The bugfix should probably be backported on top of 3.0 and released as maintenance

**Comment by jouni** [comment] 2018-06-11 11:51
Yeah, so it will eventually be included in a Vaadin 10 maintenance release.
