### ISSUE TITLE
Wrong date gets selected when giving a string value

### ISSUE THREAD

**Issue by vaadin-marcus** [vaadin/vaadin-date-picker#60] opened 2016-02-24 17:25 UTC
`<vaadin-date-picker label="Birthday" value="2000-01-01"></vaadin-date-picker>` results in
<img width="312" alt="screen shot 2016-02-24 at 9 05 13 am" src="https://cloud.githubusercontent.com/assets/883698/13294362/80d36a24-dad8-11e5-89c3-6de17c406eb9.png">

Mac Chrome / Pacific time zone

**Comment by tehapo** [comment] 2016-02-24 17:34
As a workaround you can also provide the time like done here: https://github.com/vaadin/vaadin-date-picker/commit/d9f3a24bd5b7ef01488f7b4da7a3895793b2faf1

This issue should be resolved with the upcoming change of using a `String` value instead of `Date`, see https://github.com/vaadin/vaadin-date-picker/issues/51#issuecomment-187733692.

**Comment by platosha** [comment] 2016-02-29 15:33
resolved by #69

**Closed by platosha** 2016-02-29 15:33 UTC
Labels: sprint backlog

**Comment by MarcosGalaviz** [comment] 2016-04-18 22:09
Hi I am doing this:
 <vaadin-date-picker label="Pick a date" value={{valorFecha}} id="time"></vaadin-date-picker>

But allways the Day is a day less :(, example:

if I do this in the script:

  var fechaConvertidaTimePicker = new Date(this.valorFecha);
        var year = fechaConvertidaTimePicker.getFullYear();
        var month= fechaConvertidaTimePicker.getMonth();
        var day= fechaConvertidaTimePicker.getDate();

The var: day is a day less than wich I selected :( I don't understand why :(

**Comment by jouni** [comment] 2016-04-19 06:45
HI @MarcosGalaviz

I don’t see any vaadin-date-picker specific code in your script. What does `this.valorFecha` refer to? Is it string, and what is its value?

**Comment by MarcosGalaviz** [comment] 2016-04-19 14:35
Sorry I think I write wrong my message, this is de code where I call the web component: 
` <vaadin-date-picker label="Pick a date" value={{valorFecha}} id="time"></vaadin-date-picker>` 

then `this.valorFecha` is the binding between the web component and this porperty:
` valorFecha: {
            type: String,
            value:''
        }`

And then I have this code just to check the value and I dont understand why the day is always a day less:

`var fechaConvertidaTimePicker = new Date(this.valorFecha);
        var year = fechaConvertidaTimePicker.getFullYear();
        var mes = fechaConvertidaTimePicker.getMonth();
        var dia = fechaConvertidaTimePicker.getDate();
`

I just did this to "fix" the problem adding one day to the variable: 
`var dia = fechaConvertidaTimePicker.getDate()+1;`

Thanks a lot for your help

**Comment by platosha** [comment] 2016-04-21 13:14
Hi @MarcosGalaviz,

I think the cause here is that `Date` object methods are returning date in your local timezone.

Vaadin DatePicker gives you value as an ISO string, like `'2000-01-01'`. But, `new Date('2000-01-01').getDate();` would return Dec 31 1999 if you live in western hemisphere. This is because Date constructor considers ISO string date as at UTC midnight, but methods like `getDate()` return values in local time, where it's not midnight of a new day yet.

Please try to use `getUTCFullYear()`, `getUTCMonth()`, `getUTCDate()`, that should solve the mismatch.

Given that the date picker's value is always ISO string (except for empty string), you can reliably parse it without invoking the confusing `Date` at all, like this:

```javascript
var parts = /^(\d{4}|[-+]\d{6})-(\d{2})-(\d{2})$/.exec(this.datePickerValue);
if (parts) {
  var year = parseInt(parts[1], 10);
  var month = parseInt(parts[2], 10) - 1;
  var date = parseInt(parts[3], 10);
}
```
