### ISSUE TITLE
"too much recursion" when element used in shadow root

### ISSUE THREAD

**Issue by tomalec** [vaadin/vaadin-date-picker#567] opened 2018-06-07 15:13 UTC
### Description
In Firefox `too much recursion` error is thrown when `vaadin-date-picker` is used in shadow root.

### Expected outcome
No error is thrown

### Actual outcome
error is thrown

### Live Demo
code - https://glitch.com/edit/#!/instinctive-brow?path=index.html:22:7
preview - https://instinctive-brow.glitch.me/

### Steps to reproduce
1. Create a custom element, that creates shadow root on `constructor` and appends `vaadin-date-picker` inside.
2. Open the page in Firefox.
3. Observe console

```html
<script>
customElements.whenDefined('vaadin-date-picker').then(function(){

    customElements.define('my-element', class extends HTMLElement {
        constructor() {
            super();
            this.attachShadow({
                mode: 'open'
            });
            this.vaadinElement = document.createElement('vaadin-date-picker');
            this.shadowRoot.appendChild(this.vaadinElement);
        }
    });
});
</script>

<my-element></my-element>
```
### Browsers Affected
- [ ] Chrome
- [x] Firefox
- [?] Safari
- [ ] Edge
- [ ] IE 11
- [?] iOS Safari
- [?] Android Chrome

![image](https://user-images.githubusercontent.com/17435/43387890-f7590788-93e7-11e8-8db9-85aa12e8836f.png)

**Comment by web-padawan** [comment] 2018-07-29 13:56
Thanks for the issue, and sorry for not answering earlier. We recently updated the issue template to use glitch, since `polygit` has stopped working for jsbins.

So, cold you reproduce the issue using this glitch and with the latest polyfills? Press "Remix This" to edit and apply any changes you need: https://glitch.com/edit/#!/desert-duckling

**Comment by tomalec** [comment] 2018-07-30 09:02
I also update the link above to https://glitch.com/edit/#!/instinctive-brow?path=index.html:22:7

**Comment by web-padawan** [comment] 2018-07-30 10:32
Note: stamping lots of date-pickers can be also reproduced in Edge, and is likely a `shadydom` issue.

Copying the full stack trace here, for further investigation.

<details>
  <summary>Full stack trace</summary>
  <code>
too much recursion patch-builtins.js:87:11
patch-events.js:522:2
Gd
patch-events.js:522:2
l
patch-events.js:396:6
dispatchEvent
patch-builtins.js:87:11
dispatchNotifyEvent
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:304:5
runNotifyEffect
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:334:5
runEffectsForProperty
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:147:11
runNotifyEffects
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:237:20
_propertiesChanged
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1843:11
_flushProperties
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-accessors.html.js:607:11
ready
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1793:9
ready
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/element-mixin.html.js:740:9
ready
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/dir-mixin.html.js:137:9
ready
https://entertaining-blade.glitch.me/bower_components/polymer/lib/legacy/legacy-element-mixin.html.js:179:9
ready
https://entertaining-blade.glitch.me/bower_components/polymer/lib/legacy/class.html.js:218:9
_enableProperties
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-accessors.html.js:587:11
__enableOrFlushClients
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1728:15
_readyClients
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1746:9
_readyClients
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/element-mixin.html.js:764:9
_flushClients
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1695:11
_propertiesChanged
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1835:9
_flushProperties
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-accessors.html.js:607:11
ready
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1793:9
ready
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/element-mixin.html.js:740:9
ready
https://entertaining-blade.glitch.me/bower_components/vaadin-date-picker/src/vaadin-date-picker-overlay-content.html.js:77:7
_enableProperties
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-accessors.html.js:587:11
__enableOrFlushClients
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1728:15
_readyClients
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1746:9
_flushClients
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1695:11
_propertiesChanged
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1835:9
_flushProperties
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-accessors.html.js:607:11
ready
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1793:9
_enableProperties
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-accessors.html.js:587:11
TemplateInstanceBase
https://entertaining-blade.glitch.me/bower_components/polymer/lib/utils/templatize.html.js:83:9
klass
https://entertaining-blade.glitch.me/bower_components/polymer/lib/utils/templatize.html.js:837:19
TemplateInstance
https://entertaining-blade.glitch.me/bower_components/polymer/lib/utils/templatize.html.js:837:19
_templateChanged
https://entertaining-blade.glitch.me/bower_components/vaadin-overlay/src/vaadin-overlay.html.js:552:24
runMethodEffect
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:883:14
runEffectsForProperty
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:147:11
runEffects
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:109:13
_propertiesChanged
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1840:9
_flushProperties
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-accessors.html.js:607:11
_invalidateProperties
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1661:11
_setProperty
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1646:11
_createPropertyAccessor/<.set<
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-accessors.html.js:463:15
_setTemplateFromNodes
https://entertaining-blade.glitch.me/bower_components/vaadin-overlay/src/vaadin-overlay.html.js:243:23
OverlayElement/this._observer<
https://entertaining-blade.glitch.me/bower_components/vaadin-overlay/src/vaadin-overlay.html.js:199:9
flush
https://entertaining-blade.glitch.me/bower_components/polymer/lib/utils/flattened-nodes-observer.html.js:248:9
ready
https://entertaining-blade.glitch.me/bower_components/vaadin-overlay/src/vaadin-overlay.html.js:215:7
_enableProperties
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-accessors.html.js:587:11
connectedCallback
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/element-mixin.html.js:718:9
connectedCallback
https://entertaining-blade.glitch.me/bower_components/vaadin-overlay/src/vaadin-overlay.html.js:267:7
te.prototype.connectedCallback
CustomElementInternals.js:303:6
O
CustomElementInternals.js:86:8
of/<
Node.js:66:12
_attachDom
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/element-mixin.html.js:788:13
_readyClients
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/element-mixin.html.js:755:23
_flushClients
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1695:11
_propertiesChanged
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1835:9
_flushProperties
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-accessors.html.js:607:11
ready
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1793:9
ready
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/element-mixin.html.js:740:9
ready
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/dir-mixin.html.js:137:9
ready
https://entertaining-blade.glitch.me/bower_components/polymer/lib/legacy/legacy-element-mixin.html.js:179:9
ready
https://entertaining-blade.glitch.me/bower_components/polymer/lib/legacy/class.html.js:218:9
ready
https://entertaining-blade.glitch.me/bower_components/polymer/lib/legacy/class.html.js:218:9
ready
https://entertaining-blade.glitch.me/bower_components/vaadin-date-picker/src/vaadin-date-picker-mixin.html.js:271:5
ready
https://entertaining-blade.glitch.me/bower_components/vaadin-control-state-mixin/vaadin-control-state-mixin.html.js:89:5
ready
https://entertaining-blade.glitch.me/bower_components/vaadin-date-picker/src/vaadin-date-picker.html.js:128:7
_enableProperties
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-accessors.html.js:587:11
connectedCallback
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/element-mixin.html.js:718:9
connectedCallback
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/dir-mixin.html.js:147:11
connectedCallback
https://entertaining-blade.glitch.me/bower_components/polymer/lib/legacy/legacy-element-mixin.html.js:79:9
connectedCallback
https://entertaining-blade.glitch.me/bower_components/vaadin-date-picker/src/vaadin-date-picker-mixin.html.js:292:5
connectedCallback
https://entertaining-blade.glitch.me/bower_components/vaadin-control-state-mixin/vaadin-control-state-mixin.html.js:136:5
te.prototype.connectedCallback
CustomElementInternals.js:303:6
O
CustomElementInternals.js:86:8
of/<
Node.js:81:8
<анонимная>
https://entertaining-blade.glitch.me/:19:9
xe
CustomElementInternals.js:266:21
Be
CustomElementRegistry.js:186:6
p.define/<
CustomElementRegistry.js:130:32
R/this.ja
CustomElementRegistry.js:38:32
p.Za/this.ja/<
CustomElementRegistry.js:252:47
Ch
post-polyfill.js:33:6
f/</<
html-imports.js:612:63
d/</<
html-imports.js:648:8
h
html-imports.js:579:18
d/<
html-imports.js:646:28
n
html-imports.js:44:6
d
html-imports.js:646:4
f/<
html-imports.js:612:28
b
html-imports.js:626:8
e
html-imports.js:630:4
f
html-imports.js:612:4
<анонимная>
post-polyfill.js:40:4
p.Za/this.ja
CustomElementRegistry.js:252:35
p.define
CustomElementRegistry.js:130:6
dh.define
style-placeholder.js:35:4
createOverlayContent
https://entertaining-blade.glitch.me/bower_components/vaadin-overlay/src/vaadin-overlay.html.js:42:5
_templateChanged
https://entertaining-blade.glitch.me/bower_components/vaadin-overlay/src/vaadin-overlay.html.js:587:33
runMethodEffect
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:883:14
runEffectsForProperty
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:147:11
runEffects
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:109:13
_propertiesChanged
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1840:9
_flushProperties
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-accessors.html.js:607:11
_invalidateProperties
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1661:11
_setProperty
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1646:11
_createPropertyAccessor/<.set<
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-accessors.html.js:463:15
_setTemplateFromNodes
https://entertaining-blade.glitch.me/bower_components/vaadin-overlay/src/vaadin-overlay.html.js:243:23
OverlayElement/this._observer<
https://entertaining-blade.glitch.me/bower_components/vaadin-overlay/src/vaadin-overlay.html.js:199:9
flush
https://entertaining-blade.glitch.me/bower_components/polymer/lib/utils/flattened-nodes-observer.html.js:248:9
ready
https://entertaining-blade.glitch.me/bower_components/vaadin-overlay/src/vaadin-overlay.html.js:215:7
_enableProperties
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-accessors.html.js:587:11
connectedCallback
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/element-mixin.html.js:718:9
connectedCallback
https://entertaining-blade.glitch.me/bower_components/vaadin-overlay/src/vaadin-overlay.html.js:267:7
te.prototype.connectedCallback
CustomElementInternals.js:303:6
O
CustomElementInternals.js:86:8
of/<
Node.js:66:12
_attachDom
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/element-mixin.html.js:788:13
_readyClients
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/element-mixin.html.js:755:23
_flushClients
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1695:11
_propertiesChanged
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1835:9
_flushProperties
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-accessors.html.js:607:11
ready
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/property-effects.html.js:1793:9
ready
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/element-mixin.html.js:740:9
ready
https://entertaining-blade.glitch.me/bower_components/polymer/lib/mixins/dir-mixin.html.js:137:9
ready
https://entertaining-blade.glitch.me/bower_components/polymer/lib/legacy/legacy-element-mixin.html.js:179:9
ready
https://entertaining-blade.glitch.me/bower_components/polymer/lib/legacy/class.html.js:218:9
</code>
</details>

**Comment by web-padawan** [comment] 2018-08-16 11:13
Also happens in `vaadin-list-mixin`: https://travis-ci.org/vaadin/vaadin-list-mixin/builds/411173544

**Comment by web-padawan** [comment] 2021-03-08 20:32
This issue is quite outdated and was most likely caused by old polyfill version. Closing as wontfix.

**Closed by web-padawan** 2021-03-08 20:32 UTC
