### ISSUE TITLE
enhancement: add date time picker

### ISSUE THREAD

**Issue by KrifaYounes** [vaadin/vaadin-date-picker#593] opened 2018-07-27 13:57 UTC
it's possible to a vaadin-date-time-picker
user can select date and hour with minutes 
it's very used for flights
thanks

**Comment by web-padawan** [comment] 2018-07-27 15:19
Thanks for the issue. Closing as a duplicate of #245 so closing in favour of that.

We already have `vaadin-time-picker` component which is at alpha stage, feel free to try it and submit your feedback to https://github.com/vaadin/vaadin-time-picker

**Closed by web-padawan** 2018-07-27 15:19 UTC
