### ISSUE TITLE
Date picker is not scrolled properly on iPad

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-date-picker#321] opened 2017-01-15 12:26 UTC
![output3](https://cloud.githubusercontent.com/assets/6059356/21962431/7cc443de-db2e-11e6-804e-3cbd9a3f8022.gif)

**Comment by tomivirkki** [comment] 2017-01-16 08:31
Closing as a duplicate of #200

**Closed by tomivirkki** 2017-01-16 08:31 UTC
Labels: bug, in progress
