### ISSUE TITLE
Edge Dropdown Bug

### ISSUE THREAD

**Issue by ryanburns23** [vaadin/vaadin-date-picker#416] opened 2017-08-24 16:50 UTC
### Description
When using the date picker on Edge it continuously opens when you try and close it

![vaadin](https://user-images.githubusercontent.com/17202389/29677558-5360e6de-88b0-11e7-8d77-1a6e3fdabc5f.gif)

### Steps to reproduce
Use vaadin-date-picker v2.0.2 in polymer 2 on Edge

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [x] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

I was able to fix this locally by removing `this.open()` from `_onUserInput()`
https://github.com/vaadin/vaadin-date-picker/blob/7c62532202b785939e4885c44125eaab06ca09e1/vaadin-date-picker-mixin.html#L744

Hope this helps. Thanks for the great components

**Comment by jouni** [comment] 2017-08-28 13:52
Possibly related: https://github.com/vaadin/vaadin-combo-box/issues/506

**Comment by manolo** [comment] 2017-09-13 05:54
Hi, I tried to reproduce the issue and it does not happen anymore. Probably some fix in text-field might fix it.
Please do you mind to check whether it has gone by visiting the vaadin-date-picker [demo](https://cdn.vaadin.com/vaadin-date-picker/2.0.3/demo/index.html) page?

Here a screenshot with it working in my system:
http://recordit.co/Koht1irQAY/gif/notify

**Comment by manolo** [comment] 2017-09-13 08:20
Double checked by @YuriyVaadin and couldn't reproduce. 
Closing, @ryanburns23 feel free to reopen if you continue having the issue.

**Closed by manolo** 2017-09-13 08:20 UTC
Labels: bug, feedback, sprint backlog
