### ISSUE TITLE
Clear icon is shown when bound to a null value

### ISSUE THREAD

**Issue by vaadin-marcus** [vaadin/vaadin-date-picker#63] opened 2016-02-24 21:43 UTC
I would expect that just an empty field is shown for both null and empty values.

**Comment by Saulis** [comment] 2016-02-29 15:29
Seems to be currently only reproducable with `undefined` value, empty string and `null` seem to work. `undefined` is also fixed on #69

**Closed** 2016-02-29 15:29 UTC
Labels: in review
