### ISSUE TITLE
checkValidity gets called with wrong values + 2 many times 

### ISSUE THREAD

**Issue by punkratz312** [vaadin/vaadin-date-picker#617] opened 2018-11-08 09:41 UTC
After I select a date the checkValidity function gets called the first time with the correct value. Right after that it gets called 2 times again with a wrong date. I selected 1 Feb 2020. Right after the first validation is done, its getting called right again with the wrong value.

![image](https://user-images.githubusercontent.com/8830888/48190267-90b61980-e342-11e8-9b8c-137e91ed04d0.png)

**Comment by punkratz312** [comment] 2018-11-08 15:46
@tomivirkki it actually only happens if the selected date is in the next year. I printed out the given value in console for every call.
The fist date is always the correct one the ones following, not.

![image](https://user-images.githubusercontent.com/8830888/48209612-e48e2600-e375-11e8-841f-ef1460ae3c40.png)

**Comment by tomivirkki** [comment] 2019-07-19 12:54
Closing as still can't reproduce this. Please re-open if this is still an issue and preferably provide a runnable code-example on how to reproduce it.

**Closed by tomivirkki** 2019-07-19 12:54 UTC
