### ISSUE TITLE
[Bug] Autopen calendar inside notification.

### ISSUE THREAD

**Issue by alejandro7x** [vaadin/vaadin-date-picker#775] opened 2020-10-07 00:51 UTC
### Description
Wrong location of the datepicker overlay added to a layout within a notification when calling dp.open() in the constructor

### Expected outcome
The overlay of the datepicker opens in the correct position just below the element.

### Actual outcome
The overlay opens in a different position than the correct one.

### Steps to reproduce
1. Add a datepicker to a vertical layout.
2. Set the vertical layout to open itself on the event 'addAttachListener()'
3. Add the vertical layout to the notification.
4. Open the notification.

### Browsers Affected
- [ X] Chrome
- [ X] Firefox
- [ X] Safari
- [ X] Edge
- [ X] IE 11
- [ X] iOS Safari
- [ X] Android Chrome

**Comment by web-padawan** [comment] 2020-10-08 09:02
Thanks for the issue, this looks like a duplicate of #755 which is also about using a date picker in the notification.

We recommend to consider using `Dialog` instead of `Notification` which is a better fit for this case.

**Closed by web-padawan** 2020-10-08 09:02 UTC
