### ISSUE TITLE
Datetime picker

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-date-picker#245] opened 2016-10-03 07:28 UTC
Add the option to choose time together with the date.

If you feel strongly that vaadin-date-picker should have an option for an integrated time picker, add a “thumbs up (+1)” reaction to this issue.

**Comment by rubenstolk** [comment] 2016-10-04 16:02
(+1)

**Comment by elion** [comment] 2017-01-20 13:10
+1

**Comment by macjuan** [comment] 2017-02-10 12:00
I am quite much opposed to this, especially if the UI design would be inherited from Vaadin Framework's component. Done elegantly, perhaps.

**Comment by jouni** [comment] 2017-02-10 14:30
Well, we wouldn’t of course just bolt it on that crudely. I think it would be a separate overlay from the current month list.

I can do some preliminary ideation and mockups to get the discussion started.

**Comment by prateeklal** [comment] 2017-07-05 08:13
Any updates on the time picker yet?

**Comment by basvanbeek** [comment] 2017-09-10 14:54
to make a combined date time picker really useful to me it would also allow the option to display and set seconds and even milliseconds (not just hours and minutes).

**Comment by letrthang** [comment] 2017-10-15 08:15
Vote. This is useful to design a Timer.

**Comment by Zynde** [comment] 2017-10-15 09:52
+1

**Comment by chaspi** [comment] 2017-10-20 12:32
+1

**Comment by heruan** [comment] 2017-11-09 08:23
I would rather create a `vaadin-time-picker` and then a `vaadin-datetime-picker` which use them both, to cover these use cases:

1. select time only or a range of time within a day;
2. select a date and a time range within the day (one date-picker, two time-pickers);
3. select a full timestamp (one datetime-picker) or a range (two datetime-pickers).

This would also fit well passing the values to backend strong-type frameworks (e.g. Java's `Zoned`/`LocalDateTime`, `LocalDate`, `LocalTime`).

**Comment by macjuan** [comment] 2017-11-09 12:35
I think at this time it would be great to have a solution for picking time. It may be in the form of what @heruan suggests or then we do just a combined UI object that has a text field that can have 1) date picker 2) time picker 3) both date and time picker.

**Comment by letrthang** [comment] 2017-11-10 04:24
Time and datetime are very usual used in UI design. So i believe it is worth to make 2 different UI components for each of them. Because in theory, Time is a repeatable value but Datetime is not, so creating 2 different components make it easy for programming also.
Thanks

**Comment by jouni** [comment] 2018-01-15 07:34
Happy to report that we are finally starting to work on these components! If you have some specific use cases you think we should consider, please add them here!

**Comment by basvanbeek** [comment] 2018-01-15 09:16
Actual use case: a lot of the applications we build (participatory sports events) deal with single points in time to designate boundaries of allowed/disallowed timestamps and set by non technical users (minimum accepted date-time, maximum accepted date-time, gun times (when categories in a race start). The resolution in which this needs to be set is typically hundreds or milliseconds.

<img width="507" alt="min. accepted time" src="https://user-images.githubusercontent.com/7205296/34935078-f25163c0-f9dc-11e7-9b00-192a39261edf.png">

**Comment by lpellegr** [comment] 2018-01-15 09:20
In our case, we have date and time picker for scheduling post-publication.
This context does not require seconds and milliseconds precision. However,
we use 24-hour format.

Le lun. 15 janv. 2018 à 10:16, Bas van Beek <notifications@github.com> a
écrit :

**Comment by heruan** [comment] 2018-01-15 09:32
Most of our use cases are described in my comment [above](https://github.com/vaadin/vaadin-date-picker/issues/245#issuecomment-343080743). Here some additional details:

1. when selecting the time from the dropdown/popup, we often just need a subset of minutes e.g. `10:00`-`10:15`-`10-30`-`10:45` with a configurable *step* value;
2. manual typing of both date and time can increase the form compilation speed a lot for accustomed users, e.g. typing `10` -> `10:00` or `1045` -> `10:45` (ideal would be also an auto rounding on the configured *step* value, e.g. `1037` -> `10:45`).

I don't expect a build-in feature for 2, but an easy way to hook-in with custom callbacks would be ideal.

**Comment by brettpostin** [comment] 2018-01-30 13:15
@jouni great to hear work has started on these. Do you have a rough idea of when they may be available at this stage?

**Comment by jouni** [comment] 2018-02-07 13:42
@brettpostin sorry for the delay. I’ve been sitting on the design for a while now, and the rest of the team has still been busy getting all the existing elements ready for beta.

Beta releases are happening this week, and I’m trying to provide the first design iteration this week as well. Just as a heads up, we are going to start pretty small, just with a simple time picker.

**Comment by heruan** [comment] 2018-03-17 16:57
Since I'm facing this requirement right now, I'll put it here as an additional use case: when application users are from different time zones, a date-time picker should have also a time zone selector to let the use specify relative to which zone he's inputting time.

**Comment by sebastianroming** [comment] 2018-04-09 08:09
+1 

@jouni any news about a time picker implementation right now?

**Comment by jouni** [comment] 2018-04-09 12:12
🙈 I feel embarrassed, getting everyone’s hopes up prematurely, it seems. These components were on the roadmap for Q1, but it seems other priorities were still more pressing (like the Vaadin 10 release). And now Polymer 3 support is the top priority. So, implementation hasn’t actually started yet 😞 

@heruan, thanks. Timezone support has been on the feature list from the get-go. Not sure if that’ll be part of the very first iteration, though.

I can only share the designs I’ve managed to put together in the meantime. These are just proposals, and we don’t have decisions about the scope of the first iteration. I’m expecting that we will start with just the time picker (so no combined datetime picker yet), and the UI might be even as simple as two/three combo boxes put together.

Design document: https://docs.google.com/document/d/1M7OWaR8ahzDxYg1ZmJL4rxHk5fnXhwWp6sO_BDnE8ok/edit#heading=h.3ty1iicivt
Time picker mockups: https://www.figma.com/file/Iu80kV7deFz5qUgjDq1nVWts/Time-picker
Time picker HTML & CSS prototype: http://output.jsbin.com/zaxewec

**Comment by letrthang** [comment] 2018-04-09 13:31
I think we need wait till Vaadin 10 release. Seems that now Vaadin is putting all resource to Vaadin 10  :))

**Comment by mstahv** [comment] 2019-04-26 07:23
Created a rudimentary field to edit LocalDateTime to Flow Viritin. With converter it can be used to edit java.util.Date too. I hope it helps people until this very much needed feature lands to official releases.

**Comment by sebastianroming** [comment] 2019-06-06 12:01
@jouni What's the current status of this? Would be awesome to use a date and time picker and not to hack sth.

**Comment by web-padawan** [comment] 2019-06-06 12:17
@sebastianroming you can use `vaadin-custom-field` to create date-time picker.
See https://cdn.vaadin.com/vaadin-custom-field/1.0.4/demo/#custom-field-advanced-demos

```html
  <vaadin-custom-field label="Invoice date">
    <vaadin-date-picker></vaadin-date-picker>
    <vaadin-time-picker></vaadin-time-picker>
  </vaadin-custom-field>
```

**Comment by sebastianroming** [comment] 2019-06-06 12:29
@web-padawan Yes, I already stumbled on this... but a generic date-time-picker would be even more awesome ;-)

**Comment by sebastianroming** [comment] 2019-06-06 12:51
@web-padawan tried your example now:

```
vaadin-text-field.js:138 Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry
    at http://localhost:8082/node_modules/@vaadin/vaadin-time-picker/node_modules/@vaadin/vaadin-text-field/src/vaadin-text-field.js:138:16
```

Using

```
import { LitElement, html } from 'lit-element';
import '@vaadin/vaadin-date-picker';
import '@vaadin/vaadin-time-picker';

class LdDatepicker extends LitElement {

  static get properties() { return {}; }

  render() {
    return html`
      <vaadin-custom-field label="Date range from">
        <vaadin-date-picker id="startFrom"></vaadin-date-picker>
        <vaadin-time-picker id="endFrom"></vaadin-time-picker>
      </vaadin-custom-field>

      <vaadin-custom-field label="Date range to">
        <vaadin-date-picker id="startTo"></vaadin-date-picker>
        <vaadin-time-picker id="endTo"></vaadin-time-picker>
      </vaadin-custom-field>
    `;
  }

}

customElements.define('ld-datepicker', LdDatepicker);
```

... any helpful tips?

**Comment by web-padawan** [comment] 2019-06-06 13:24
@sebastianroming first make sure you are using the latest versions.Then, do the following:

1. remove `node_modules`

2. run `npm install`

3. check that `node_modules/@vaadin` contains a flat tree

4. if not, run `npm dedupe`

That should help to remove that issue.

**Comment by moderndeveloperllc** [comment] 2019-06-06 13:31
@web-padawan It looks like the demo that you references isn't serializing the time part properly. Going to https://vaadin.com/components/vaadin-custom-field/html-examples/custom-field-advanced-demos will give you something like:

<img width="703" alt="ScreenShot 2019-06-06 at 8 29 53 AM" src="https://user-images.githubusercontent.com/1920405/59036660-5576bd00-8835-11e9-9e38-208898415267.png">

Going to your link will give:

<img width="740" alt="ScreenShot 2019-06-06 at 8 31 34 AM" src="https://user-images.githubusercontent.com/1920405/59036753-835c0180-8835-11e9-8b0d-77b6fd08dc8d.png">

**Comment by web-padawan** [comment] 2019-06-06 13:42
@moderndeveloperllc that has been recently fixed (time-picker was missing a `change` event). The website is not yet updated to latest versions.

**Comment by sebastianroming** [comment] 2019-06-06 13:48
@web-padawan nope, didn't work.

![node_modules_vaadin](https://user-images.githubusercontent.com/200112/59037893-701b5700-8872-11e9-9f76-c920024567ea.PNG)

**Comment by web-padawan** [comment] 2019-06-06 14:29
Can you share the versions you have in `package.json`?

**Comment by sebastianroming** [comment] 2019-06-06 15:00
`vaadin-date-picker: ^4.0.1`
`vaadin-time-picker: ^2.0.1`

**Comment by web-padawan** [comment] 2019-06-13 12:13
Sorry for the lack of response. Let's continue in Vaadin slack channel:
https://polymer.slack.com/messages/C6ULJ2F7S

**Comment by Waynezhi** [comment] 2019-06-19 12:34
me too, I got similar error:

> Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-lumo-styles" has already been used with this registry
>     at Module../node_modules/@vaadin/vaadin-date-picker/node_modules/@vaadin/vaadin-lumo-styles/version.js

**Comment by web-padawan** [comment] 2019-06-19 12:51
@Waynezhi please do the following steps:

1. Make sure you have latest Polymer CLI installed:

```
npm i -g polymer-cli
```

2. Remove node_modules and lockfile

```
rm -rf node_modules package-lock.json
```

3. Install dependencies again

```
npm i
```

That helped to solve the problem in the above case.

**Comment by Waynezhi** [comment] 2019-06-19 14:27
@web-padawan thx a lot, it works now

**Comment by Haprog** [comment] 2020-02-27 12:17
For anyone interested in this, there's now a feature complete alpha release of `<vaadin-date-time-picker>` web component and `DateTimePicker` Flow component. :tada:

Please take a look at the following releases and if you want to post issues or feature requests do so in the relevant repository below.

- Web component: [&lt;vaadin-date-time-picker&gt;](https://github.com/vaadin/vaadin-date-time-picker) ([releases](https://github.com/vaadin/vaadin-date-time-picker/releases), [issues](https://github.com/vaadin/vaadin-date-time-picker/issues))
- Flow component: [DateTimePicker](https://github.com/vaadin/vaadin-date-time-picker-flow) ([releases](https://github.com/vaadin/vaadin-date-time-picker-flow/releases), [issues](https://github.com/vaadin/vaadin-date-time-picker-flow/issues))

**Comment by PriyadharshiniBalavadivel** [comment] 2020-02-27 13:32
Hi,

I tried using the new DateTime Picker flow component in  our application(Vaadin version 14.1.16) and after adding the same the CSS in my application is not removed from the application. I've done a maven clean and build but still the issue exists. The CSS is added only after removing the DateTimePicker from project. Am I missing anything here?

**Comment by Haprog** [comment] 2020-02-27 13:41
@PriyadharshiniBalavadivel I didn't really understand what you're saying. What is the problem? What CSS are you talking about?

**Comment by PriyadharshiniBalavadivel** [comment] 2020-02-27 13:46
Sorry that I was not clear in my problem. The issue is that once I include the DateTimePicker in the project, all applied themes and the alignments are removed from the application. when checking the console during the build I get the following error.

npm WARN no-name@ No description
npm WARN no-name@ No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by PriyadharshiniBalavadivel** [comment] 2020-02-27 13:49
@Haprog Sorry that I was not clear in my problem. The issue is that once I include the DateTimePicker in the project, all applied themes and the alignments are removed from the application. when checking the console during the build I get the following error.

npm WARN no-name@ No description
npm WARN no-name@ No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by Haprog** [comment] 2020-02-28 07:41
@PriyadharshiniBalavadivel If you can provide a small demo project that reproduces the issue, please open an issue about it at https://github.com/vaadin/vaadin-date-time-picker-flow/issues

But the warnings you pasted don't seem to be related to the issue in any way (and they probably happen also without DateTimePicker). I've seen the same warnings in many non-Vaadin projects too. `fsevents` is a library to detect changes to files (often used for development mode to implement file watching to trigger automatic rebuilds or reloads when some source files are changed). But fsevents is macOS specific so other means of file change detection are used on other platforms.

**Comment by PriyadharshiniBalavadivel** [comment] 2020-02-28 09:50
@Haprog I'm not sure if it was a problem with my eclipse. When building the project the demo project has been added to my npm folders (still not able to figure it out on how that happened ). After removing those files related to demo and then rebuilding the project cleared the issue. Now the issue is not repeated in my subsequent builds. Thank you for your time

**Comment by web-padawan** [comment] 2020-05-06 07:34
`vaadin-date-time-picker` 1.0.0 has been released 🎉 Check out the release notes:
https://github.com/vaadin/vaadin-date-time-picker/releases/tag/v1.0.0

Please submit any feature requests, bug reports and feedback to the repo linked above.

Closing as done.

**Closed by web-padawan** 2020-05-06 07:34 UTC
Labels: epic
