### ISSUE TITLE
Date not getting selected in webcomponents .org

### ISSUE THREAD

**Issue by rkief** [vaadin/vaadin-date-picker#426] opened 2017-09-09 13:15 UTC
### Description
The `vaadin-date-picker` element does not return a date in the overview of the webcomponents.org site.  Also, does not return when export to JSFiddle is selected.

Having this same problem in  my application after upgrading.  Moving back to alpha1 did not help.

Element is not even displayed in FF, Edge or IE11.

### Expected outcome
Date should be returned when selected.

### Actual outcome
No date returned.

### Live Demo
https://www.webcomponents.org/element/vaadin/vaadin-date-picker

### Steps to reproduce
Using Chrome Version 62.0.3202.9 (Official Build) dev (64-bit)

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [X] Edge
- [X] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by limonte** [comment] 2017-09-12 06:29
Hi @rkief and thanks for reaching us out!

Could you please clarify what do you mean by "element does not return a date in the overview"?

For me https://www.webcomponents.org/element/vaadin/vaadin-date-picker works fine both in Chrome and Firefox:

![recorded](https://user-images.githubusercontent.com/6059356/30311196-d0a15872-979c-11e7-88d7-db82f047e7a9.gif)

**Comment by ppark482** [comment] 2017-09-25 20:50
@limonte 
![screen shot 2017-09-25 at 4 46 51 pm](https://user-images.githubusercontent.com/8863462/30830198-29adfc62-a211-11e7-93ef-4766892d228b.png)

looks like Vaadin.ThemableMixin isn't being pulled in correctly. 

I'm running into the same issues as @rkief except that I'm on Version 62.0.3202.18 (Official Build) beta (64-bit) of Chrome.

Pulling v2.0.4 of the datepicker into my application is not throwing any errors in my console but the dates are not selectable and the value attribute is not populated when a date is selected

**Comment by web-padawan** [comment] 2017-12-24 19:47
I'm unable to reproduce this issue with the current latest `2.0.7` version [webcomponents.org](https://www.webcomponents.org/element/vaadin/vaadin-date-picker) demo. And these errors mentioned above no longer appear in Firefox starting from the `2.0.5` release. Therefore I am closing this issue.

**Closed by web-padawan** 2017-12-24 19:47 UTC
