### ISSUE TITLE
styling broken in Chrome and Safari on OSX

### ISSUE THREAD

**Issue by JoernT** [vaadin/vaadin-date-picker#559] opened 2018-05-29 17:19 UTC
### Description
Rendering of date picker is broken on Chrome and Safari (latest versions) on OSX 10.13.4. However rendering is fine on Firefox.

### Expected outcome
expected to be rendered as a small grey box with icon

### Actual outcome
i attached a screenshot showing the rendering.

### Steps to reproduce

1. insert a 'vaadin-date-picker' in the template of a basic Polymer 2 web component
2. use basic component in a demo html page
3. open demo page

### Browsers Affected

- [x ] Chrome
- [ ] Firefox
- [ x] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome
![datepicker](https://user-images.githubusercontent.com/484059/40674463-3bc065a4-6375-11e8-92cd-2c6d89a88eb9.png)

**Comment by jouni** [comment] 2018-05-30 06:21
Are you by any chance placing the date picker inside a flex container that stretches the whole app? I mean, that looks like a date picker that just has a very large height (it’s supposed to look like that in that case).

**Comment by JoernT** [comment] 2018-05-30 09:57
I used it inside of a component template (Polymer 2) which has a host matcher with 'display:block;'. I inspected the elements and couldn't find anything with flex.

Further - and i should have mentioned that - in this display the overlay is broken and just displayed with zero height.

**Comment by web-padawan** [comment] 2018-07-30 06:57
Closing as a duplicate of vaadin/vaadin-text-field#237

Please feel free to reopen if you are able to reproduce using this glitch (click "Remix This" to edit it): https://glitch.com/edit/#!/desert-duckling

**Closed by web-padawan** 2018-07-30 06:57 UTC
