### ISSUE TITLE
Fullscreen popup not actually fullscreen (Android)

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-date-picker#169] opened 2016-04-21 07:54 UTC
If you have the software keyboard visible right before you tap a vaadin-date-picker and open it, the date picker fullscreen popup only covers half of the screen on an Android phone.

![screen shot 2016-04-21 at 10 50 56](https://cloud.githubusercontent.com/assets/66382/14701710/53b63fcc-07af-11e6-9a10-b965c4f90164.png)

Here’s a video of the same thing: https://drive.google.com/file/d/0BzNRYMf7bO7kbmV1b1hIMkNib28/view?usp=sharing

**Comment by Saulis** [comment] 2016-06-08 12:13
Can't reproduce this – tried with varying version all the way down to `1.0.0-alpha3` on a Nexus 5X and latest expense manager. Closing for now, please reopen if problem still occurs.

**Closed by Saulis** 2016-06-08 12:13 UTC
