### ISSUE TITLE
DatePicker not keyboard-entry friendly

### ISSUE THREAD

**Issue by guttormvik** [vaadin/vaadin-date-picker#701] opened 2020-02-18 14:57 UTC
Our users want to write values with keyboard and tab to the next field.
The DatePicker / vaadin-date-picker breaks this flow. The user writes a date in the exact format required, but when the user tabs out, the focus ends up in the overlay and they must press return to select.

Another way the DatePicker is not keyboard friendly is that if you write the date, you have to write it fully. In our Vaadin8 app, the users can write "1802" and with our server-side handleUnparsableDateString override it gets expanded to "18.02.2020".
It would be nice to have something like this in the Vaadin14 DatePicker as well

**Comment by web-padawan** [comment] 2020-02-19 07:23
Thanks for the issue. Transferred to the correct repository.

> The user writes a date in the exact format required, but when the user tabs out, the focus ends up in the overlay

This is actually by design. User has to press <kbd>Enter</kbd> to confirm date and then <kbd>Tab</kbd>.

I agree it might be inconvenient. So we are working on opt-in API called `auto-open-disabled` that would allow to type date and use <kbd>Tab</kbd> without opening overlay at all. Please see #694

> In our Vaadin8 app, the users can write "1802" and with our server-side handleUnparsableDateString override it gets expanded to "18.02.2020".

This sounds like a duplicate of vaadin/vaadin-date-picker-flow#136.
Please see https://github.com/vaadin/vaadin-date-picker-flow/issues/136#issuecomment-432562773

**Comment by web-padawan** [comment] 2020-02-25 11:37
Closing in favor of #704 and vaadin/vaadin-date-picker-flow#136 per above comment.

**Closed by web-padawan** 2020-02-25 11:37 UTC
Labels: design
