### ISSUE TITLE
Wrong click events when inside scroll container

### ISSUE THREAD

**Issue by fleckdalm** [vaadin/vaadin-date-picker#134] opened 2016-03-21 11:17 UTC
If i put the component inside a scroll container and scroll down a bit the dialog is wrongly positioned and moreover all click events lead to wrong results (e.g. wrong day clicked).

**Comment by tomivirkki** [comment] 2016-03-22 11:48
Hi, seems that the dropdown wasn't repositioned/realigned on the container scroll. Fixed that in #137 (merged to master branch now).
Does the change also fix the click issue you mentioned (couldn't reproduce it myself)?

**Comment by fleckdalm** [comment] 2016-03-23 08:15
Thanks!
Unfortunately it didn't resolve the click issue but I think it is related to #133

**Comment by jounik** [comment] 2016-04-07 12:13
@fleckdalm, would it be possible to get a test case for this (jsbin, plunkr, etc.), so that we could reproduce it?

**Comment by fleckdalm** [comment] 2016-04-07 12:18
@jounik the issue is definitely related to #133. It happens when a new stacking context is created.

**Comment by Saulis** [comment] 2016-07-27 12:30
@fleckdalm are you still having the issue? Could you provide us with an example app where this occurs?

**Comment by fleckdalm** [comment] 2016-07-27 13:04
@Saulis thank you for the follow up but, as I already mentioned, the issue is related to #133. So if you resolve the other issue this willl get resolved as well.

**Comment by platosha** [comment] 2017-05-26 10:25
Probably fixed by #347.

Closing for now. Feel free to reopen if still relevant.

**Closed by platosha** 2017-05-26 10:25 UTC
